// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Products.Infrastructure;

#nullable disable

namespace Products.Infrastructure.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    partial class ProductDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Products.Domain.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("BannerUrl")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasDefaultValue("https://via.placeholder.com/500x100.png");

                    b.Property<DateTime>("CreationDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValue(new DateTime(2022, 7, 2, 5, 44, 14, 734, DateTimeKind.Utc).AddTicks(3013));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<string>("IconUrl")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasDefaultValue("https://via.placeholder.com/100.png");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("ModificationDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValue(new DateTime(2022, 7, 2, 5, 44, 14, 734, DateTimeKind.Utc).AddTicks(3124));

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("integer");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = false,
                            BannerUrl = "https://via.placeholder.com/500x200.png",
                            CreationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Aliqua consequat labore elit eiusmod nostrud laborum consequat. Consectetur laborum adipisicing duis ad nulla enim. Esse magna adipisicing fugiat aliqua ea commodo quis anim laboris aliqua fugiat ad. Dolore elit pariatur qui excepteur culpa sit aliqua ea Lorem. Sunt laborum ut sunt cillum reprehenderit do qui nisi.\r\n",
                            Link = "qui",
                            ModificationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Priority = 1,
                            Title = "veniam"
                        },
                        new
                        {
                            Id = 2,
                            Active = false,
                            BannerUrl = "https://via.placeholder.com/500x200.png",
                            CreationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Ut laborum ex laboris do anim adipisicing in adipisicing ea aliquip. In incididunt occaecat do incididunt id sunt eiusmod ut ipsum veniam cupidatat ullamco. Amet non aute cupidatat duis veniam veniam proident in.\r\n",
                            Link = "magna",
                            ModificationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Priority = 5,
                            Title = "proident"
                        },
                        new
                        {
                            Id = 3,
                            Active = true,
                            BannerUrl = "https://via.placeholder.com/500x200.png",
                            CreationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Fugiat dolor qui duis non enim cupidatat eu exercitation Lorem non commodo incididunt ullamco commodo. In tempor ad cillum ad. Id elit aute fugiat nulla pariatur laborum. Nisi sit eiusmod do laborum ex officia duis Lorem aliqua. Tempor magna ipsum nostrud amet labore.\r\n",
                            Link = "eiusmod",
                            ModificationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Priority = 2,
                            Title = "sunt"
                        },
                        new
                        {
                            Id = 4,
                            Active = true,
                            BannerUrl = "https://via.placeholder.com/500x200.png",
                            CreationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Consectetur adipisicing ex pariatur ex aliquip eu occaecat nulla est. Nostrud voluptate mollit ad duis nulla ullamco laboris. Cillum quis qui minim veniam amet ad laboris exercitation amet. Et cillum fugiat officia in labore aliquip tempor occaecat. Anim ut fugiat nisi sit enim. Adipisicing consectetur elit non eu adipisicing.\r\n",
                            Link = "voluptate",
                            ModificationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Priority = 7,
                            Title = "aute"
                        },
                        new
                        {
                            Id = 5,
                            Active = false,
                            BannerUrl = "https://via.placeholder.com/500x200.png",
                            CreationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Anim amet esse adipisicing ut nostrud Lorem exercitation anim anim. Excepteur aliqua qui eu sint cillum consequat quis irure. Dolor amet reprehenderit nulla sunt velit occaecat est. Nisi ut ipsum pariatur reprehenderit.\r\n",
                            Link = "qui",
                            ModificationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Priority = 9,
                            Title = "occaecat"
                        },
                        new
                        {
                            Id = 6,
                            Active = false,
                            BannerUrl = "https://via.placeholder.com/500x200.png",
                            CreationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Aliquip quis aute occaecat proident magna et excepteur. Consectetur magna ut Lorem ut excepteur labore ipsum. Laborum veniam do sunt cupidatat anim mollit exercitation esse consequat excepteur duis excepteur.\r\n",
                            Link = "ipsum",
                            ModificationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Priority = 4,
                            Title = "do"
                        },
                        new
                        {
                            Id = 7,
                            Active = true,
                            BannerUrl = "https://via.placeholder.com/500x200.png",
                            CreationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Amet tempor ex fugiat velit aliquip id commodo eiusmod ad eiusmod aute anim. Exercitation incididunt est duis esse ex Lorem ea nulla anim est labore cupidatat aute. Ea ipsum id reprehenderit esse veniam velit magna aute laboris consectetur tempor occaecat. Incididunt officia laborum incididunt laboris.\r\n",
                            Link = "enim",
                            ModificationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentCategoryId = 2,
                            Priority = 10,
                            Title = "laborum"
                        },
                        new
                        {
                            Id = 8,
                            Active = false,
                            BannerUrl = "https://via.placeholder.com/500x200.png",
                            CreationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Lorem ipsum deserunt pariatur sunt incididunt reprehenderit enim et consectetur nulla sunt. Officia eiusmod culpa deserunt non aliquip laboris in laborum ullamco est dolore in esse. Aliquip qui dolor in irure excepteur et sunt ea duis proident aliqua adipisicing sint. Mollit sit et do excepteur.\r\n",
                            Link = "do",
                            ModificationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentCategoryId = 2,
                            Priority = 7,
                            Title = "tempor"
                        },
                        new
                        {
                            Id = 9,
                            Active = false,
                            BannerUrl = "https://via.placeholder.com/500x200.png",
                            CreationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Lorem ipsum deserunt pariatur sunt incididunt reprehenderit enim et consectetur nulla sunt. Officia eiusmod culpa deserunt non aliquip laboris in laborum ullamco est dolore in esse. Aliquip qui dolor in irure excepteur et sunt ea duis proident aliqua adipisicing sint. Mollit sit et do excepteur.\r\n",
                            Link = "do",
                            ModificationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentCategoryId = 2,
                            Priority = 7,
                            Title = "consectetur"
                        },
                        new
                        {
                            Id = 10,
                            Active = false,
                            BannerUrl = "https://via.placeholder.com/500x200.png",
                            CreationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Lorem ipsum deserunt pariatur sunt incididunt reprehenderit enim et consectetur nulla sunt. Officia eiusmod culpa deserunt non aliquip laboris in laborum ullamco est dolore in esse. Aliquip qui dolor in irure excepteur et sunt ea duis proident aliqua adipisicing sint. Mollit sit et do excepteur.\r\n",
                            Link = "do",
                            ModificationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentCategoryId = 3,
                            Priority = 7,
                            Title = "Non commodo"
                        });
                });

            modelBuilder.Entity("Products.Domain.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreationDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValue(new DateTime(2022, 7, 2, 5, 44, 14, 733, DateTimeKind.Utc).AddTicks(9700));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("https://via.placeholder.com/150x150.png");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("ModificationDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValue(new DateTime(2022, 7, 2, 5, 44, 14, 733, DateTimeKind.Utc).AddTicks(9853));

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 7304,
                            Active = true,
                            CategoryId = 1,
                            Code = "consequat",
                            CreationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Consectetur occaecat non aliquip amet cillum. Excepteur cupidatat pariatur magna commodo laboris consectetur labore minim adipisicing non. Amet cillum consectetur in aute nulla consectetur minim qui. Aute deserunt et ad duis nisi mollit sunt consectetur ut. Eu quis dolore magna aute et ullamco occaecat non commodo ullamco. Elit do amet nostrud exercitation reprehenderit ut excepteur magna est aliqua.\r\n",
                            ImageUrl = "https://via.placeholder.com/300x250.png",
                            Link = "ea",
                            ModificationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 644m,
                            Title = "commodo laborum incididunt"
                        },
                        new
                        {
                            Id = 2630,
                            Active = true,
                            CategoryId = 2,
                            Code = "adipisicing",
                            CreationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sint culpa culpa reprehenderit dolore ad sit quis reprehenderit eiusmod consectetur eiusmod dolor nulla. Ullamco ut commodo Lorem labore ad ex officia esse cupidatat nostrud proident pariatur laboris. Nisi esse sint fugiat nulla do mollit elit aliqua in.\r\n",
                            ImageUrl = "https://via.placeholder.com/300x250.png",
                            Link = "ullamco",
                            ModificationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 335m,
                            Title = "sint cupidatat deserunt"
                        },
                        new
                        {
                            Id = 7504,
                            Active = true,
                            CategoryId = 4,
                            Code = "ipsum",
                            CreationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Culpa commodo irure aute dolor minim sit adipisicing. Ea culpa dolore velit pariatur adipisicing ad consectetur consequat ut. Ex cillum esse esse enim deserunt do non quis consectetur laborum amet sit incididunt sunt. Reprehenderit et amet non aliqua deserunt consequat ullamco consectetur consectetur tempor aliquip cillum dolore.\r\n",
                            ImageUrl = "https://via.placeholder.com/300x250.png",
                            Link = "ut",
                            ModificationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 856m,
                            Title = "ea cillum nisi"
                        },
                        new
                        {
                            Id = 6342,
                            Active = false,
                            CategoryId = 5,
                            Code = "ipsum",
                            CreationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Occaecat elit occaecat quis fugiat consequat elit non consequat culpa laborum veniam nulla. Ex exercitation excepteur occaecat nulla incididunt veniam anim cupidatat sunt id consectetur. Sunt occaecat consequat cupidatat laborum cupidatat.\r\n",
                            ImageUrl = "https://via.placeholder.com/300x250.png",
                            Link = "ipsum",
                            ModificationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 162m,
                            Title = "nostrud Lorem voluptate"
                        },
                        new
                        {
                            Id = 7399,
                            Active = false,
                            CategoryId = 6,
                            Code = "dolor",
                            CreationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Veniam non occaecat elit occaecat ut ea labore nostrud eu eiusmod ipsum. Aliqua anim irure est qui mollit pariatur deserunt non tempor. Laborum veniam esse ad nulla officia deserunt veniam. Ex culpa in non consequat irure.\r\n",
                            ImageUrl = "https://via.placeholder.com/300x250.png",
                            Link = "Lorem",
                            ModificationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 503m,
                            Title = "deserunt quis cupidatat"
                        },
                        new
                        {
                            Id = 3269,
                            Active = true,
                            CategoryId = 5,
                            Code = "sint",
                            CreationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Aliquip consequat aliquip mollit nostrud ut minim elit id in voluptate quis voluptate quis. Elit reprehenderit nisi elit dolor cupidatat deserunt anim. Fugiat incididunt nulla laboris reprehenderit proident id reprehenderit laborum reprehenderit pariatur ea fugiat.\r\n",
                            ImageUrl = "https://via.placeholder.com/300x250.png",
                            Link = "labore",
                            ModificationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 790m,
                            Title = "aliquip nulla nulla"
                        },
                        new
                        {
                            Id = 9859,
                            Active = false,
                            CategoryId = 6,
                            Code = "qui",
                            CreationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Amet sint nostrud nisi commodo tempor dolore proident non ullamco. Anim tempor Lorem magna officia irure exercitation Lorem Lorem id. Sunt consequat cillum eu deserunt consequat velit consectetur irure incididunt aliquip mollit elit culpa duis. Cupidatat consectetur aute officia incididunt elit sunt pariatur cillum occaecat velit qui qui ut est. Dolor est commodo laboris irure quis excepteur pariatur ad id exercitation labore. Eu non dolor in aliqua consequat dolor consequat excepteur magna minim aliquip magna. Proident consequat sint ad eiusmod elit dolore et velit.\r\n",
                            ImageUrl = "https://via.placeholder.com/300x250.png",
                            Link = "labore",
                            ModificationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 123m,
                            Title = "reprehenderit officia fugiat"
                        },
                        new
                        {
                            Id = 3641,
                            Active = true,
                            CategoryId = 6,
                            Code = "veniam",
                            CreationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Nisi tempor excepteur labore cillum consequat esse laboris cupidatat laboris. Eiusmod ut sit ex est. Velit eu nisi Lorem nisi sunt pariatur tempor enim deserunt.\r\n",
                            ImageUrl = "https://via.placeholder.com/300x250.png",
                            Link = "mollit",
                            ModificationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 815m,
                            Title = "Lorem elit nostrud"
                        },
                        new
                        {
                            Id = 7139,
                            Active = false,
                            CategoryId = 1,
                            Code = "consequat",
                            CreationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Tempor elit cillum tempor ea amet cupidatat cupidatat velit elit incididunt enim aliquip. Sunt ex dolor ipsum tempor aliqua laborum anim nisi veniam aliqua eu. Ut mollit fugiat dolor dolor eu proident qui ea amet in mollit ea in. Magna quis ex consectetur quis ex in magna excepteur voluptate ea aute labore incididunt. Qui aliquip culpa sint dolor ut cupidatat exercitation dolor nostrud minim eu tempor. Cupidatat cupidatat adipisicing laborum ea qui aute qui dolore sint in velit pariatur officia. Adipisicing et cillum aliqua nulla voluptate duis non tempor quis duis sunt ex.\r\n",
                            ImageUrl = "https://via.placeholder.com/300x250.png",
                            Link = "exercitation",
                            ModificationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 980m,
                            Title = "ea laborum duis"
                        });
                });

            modelBuilder.Entity("Products.Domain.Category", b =>
                {
                    b.HasOne("Products.Domain.Category", "ParentCategory")
                        .WithMany()
                        .HasForeignKey("ParentCategoryId");

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("Products.Domain.Product", b =>
                {
                    b.HasOne("Products.Domain.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Products.Domain.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
